In [108]:
import numpy as np
import torch

In [15]:
import matplotlib.pyplot as plt

def plot(a,b,x):
    soa = np.array([a,b,x])
    plt.figure()
    ax = plt.gca()
    ax.quiver(*np.zeros_like(soa.T), *soa.T, angles='xy', scale_units='xy', scale=1)
    ax.set_xlim([-2, 2])
    ax.set_ylim([-2, 2])
    plt.draw()
    plt.show()

In [139]:
a = torch.tensor([0.2,1])
b = torch.tensor([0.8,1])
a = a / torch.norm(a)
b = b / torch.norm(b)

x = torch.tensor([0.1,1])
x = x / torch.norm(x)
#plot(a,b,x)

In [111]:
a @ x - b @ x

tensor(0.1561)

In [112]:
np.outer(a, x) - np.outer(b, x)

array([[-0.04264519, -0.42645192],
       [ 0.01987208,  0.19872075]], dtype=float32)

In [98]:
(a @ np.outer(x, x) @ b)

0.8351489891606294

In [79]:
x

array([0.09950372, 0.99503719])

In [119]:
ab = torch.stack([a,b])
ab

tensor([[0.1961, 0.9806],
        [0.6247, 0.7809]])

In [160]:
x

tensor([0.0995, 0.9950])

In [161]:
cos = torch.nn.CosineSimilarity(dim=0, eps=1e-08)

In [168]:
c = (x / torch.norm(x)) * (((a / torch.norm(a)) * cos(a, x))-((b / torch.norm(b)) * cos(b, x)))
c

tensor([-0.0327,  0.3190])

In [173]:
c = (x / torch.norm(x)) * ((a / torch.norm(a)) * cos(a, x))
c


tensor([0.0194, 0.9711])

In [174]:
a

tensor([0.1961, 0.9806])

In [176]:
(x / torch.norm(x)) * ((a / torch.norm(a)) * cos(a, x)) - (x / torch.norm(x)) * ((b / torch.norm(b)) * cos(b, x))

tensor([-0.0327,  0.3190])